[tool.poetry]
name = "dartwork-mpl"
version = "0.1.0"
description = ""
authors = ["Sangwon <lsw91.main@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "dartwork_mpl"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
matplotlib = "^3.7.1"
numpy = "^1.24.2"
pandas = "^2.1.4"
openpyxl = "^3.1.2"
scipy = "^1.11.4"
palettable = "^3.3.3"
colorspacious = "^1.1.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
seaborn = "^0.13.2"
salib = "^1.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
